# Generated by Django 4.2.4 on 2023-09-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
