# Generated by Django 4.2.4 on 2023-10-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_friendship_created_at_alter_friendship_friend_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friends",
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
    ]
