# Generated by Django 4.2.4 on 2023-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="read_users",
        ),
        migrations.RemoveField(
            model_name="message",
            name="text",
        ),
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messengerroom",
            name="slug",
            field=models.SlugField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
